#Question. 1:
Find and print the indices of pairs of elements in the following array “a” for which the value of their sum is a multiple of 7.

In [8]:
import numpy as np

a = np.array([1, 7, 3, 10, 14, 76, 4])
for i, ele in enumerate(a):
  for j in range(i+1,len(a)):
    if((ele+a[j])%7 == 0):
      print(i,j)

0 5
1 4
2 6
3 6


#Question. 2:
Calculate the inverse of matrix A (save it as A_inv) and its dot product and element-wise multiplication with B using NumPy.

In [12]:
A = np.array([[1, 2, 0],[0, 5, 6],[7, 0, 9]])
B = np.array([[5, 6, 7],[7, 8, 9],[1, 2, 3]])

import numpy as np
# inverting the A matrix
A_inv = np.linalg.inv(A)
print("A_inv:\n",A_inv)

# dot product
dot_prod = np.dot(A,B)
print("Dot product:\n",dot_prod)

# element-wise multiplication
ele_multiplication = np.multiply(A,B)
print("Element-wise product:\n",ele_multiplication)


A_inv:
 [[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]
Dot product:
 [[19 22 25]
 [41 52 63]
 [44 60 76]]
Element-wise product:
 [[ 5 12  0]
 [ 0 40 54]
 [ 7  0 27]]


#Question. 3:
a)	Create a dataframe as df for the NumPy array “data” with column name {A,B,C,D,E}.

b)	Sort the dataframe based on column C and save it as df2. Prints the first two and last two rows of the dataframe df2 using df2.head and df2.tail.

c)	Print the df2 values only as NumPy array.


In [22]:
data = np.array([[1, 2, 3, 4, 5], [1, 8, 2, 10, 11], [4, 5, 6, 7, 8],
[7, 8, 9, 10, 11], [7, 18, 19, 10, 11]])

import pandas as pd

# Part a:
df = pd.DataFrame(data)

# Part b:
df2 = df.sort_values(by= 2)
print("first two rows:\n",df2.head(2))
print("last two rows:\n",df2.tail(2))

# Part c:
arr = df2.to_numpy()
print("Array:\n",arr)

print("Original Data:\n",df.to_numpy())

first two rows:
    0  1  2   3   4
1  1  8  2  10  11
0  1  2  3   4   5
last two rows:
    0   1   2   3   4
3  7   8   9  10  11
4  7  18  19  10  11
Array:
 [[ 1  8  2 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 7 18 19 10 11]]
Original Data:
 [[ 1  2  3  4  5]
 [ 1  8  2 10 11]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 7 18 19 10 11]]


#Question. 4:
Compute the eigen values the matrix A using np.linalg.eig . Find the spectral radius of the matrix A.

In [23]:
A = np.array([[1, 2, 0],[0, 5, 6],[7, 0, 9]])
# Eigenvalues:
eigenvalues = np.linalg.eigvals(A)

# spectral radius :
radius = max(abs(eigenvalues))

print(radius)


10.57403549813147


#Question. 5:
(a)	Compute the SVD. Use np.linalg.svd(B, full_matrices=False) to obtain the matrices U, S, and Vt. Convert the one-dimensional array S into a diagonal matrix Sigma = np.diag(S).

(b)	Reconstruct the original matrix as B_recon = U @ Sigma @ Vt. Test the accuracy of the reconstruction with np.allclose(B, B_recon, atol=1e-10) and report the Boolean result.

(c)	Using the singular values in S, compute the spectral (2-norm) condition number

In [25]:
B = np.array([[5, 6, 7], [7, 8, 9], [1, 2, 3]])

# Part a:
U, S, Vt = np.linalg.svd(B, full_matrices=False)
Sigma = np.diag(S)

# Part b:
B_recon = U @ Sigma @ Vt
print(np.allclose(B, B_recon, atol=1e-10))

# Part c:
kappa2 = S.max() / S.min()
print('κ2(B):', kappa2)

True
κ2(B): 1.2095847478372948e+16
